language: node_js
sudo: true
node_js:
- '10.13.0'

install:
  - npm i -g codecov && npm install

script: ng t thd-generic-logger --watch=false --codeCoverage=true

addons:
  chrome: stable


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

after_success:
  - codecov